#!/usr/bin/env bash
# shellcheck disable=SC1091
. /usr/local/lib/proxy-tools/proxy-core.sh

cmd="$(basename "$0")"

case "$cmd" in
  proxy-on) _proxy_on "$@" ;;
  proxy-off) _proxy_off "$@" ;;
  proxy-status|proxy-test) _proxy_status "$@" ;;
  proxy-use) _proxy_use "$@" ;;
  docker-proxy-on) _proxy_docker_on "$@" ;;
  docker-proxy-off) _proxy_docker_off "$@" ;;
  docker-proxy-restart) _proxy_docker_restart "$@" ;;
  *) _proxy_menu "$@" ;;
esac
