# shellcheck shell=bash

_PROXY_CONF="/etc/proxy-tools.conf"
_PROXY_ENV="/etc/profile.d/proxy-env.sh"
_APT_CONF="/etc/apt/apt.conf.d/99-proxy-tools.conf"
_DOCKER_CONF_DIR="/etc/systemd/system/docker.service.d"
_DOCKER_CONF="${_DOCKER_CONF_DIR}/http-proxy.conf"
_WGET_CONF="/etc/wgetrc"

_proxy_root() {
  if [ "$(id -u)" -eq 0 ]; then
    "$@"
  else
    sudo "$@"
  fi
}

_proxy_write_root_file() {
  local file="$1"
  local tmp
  tmp="$(mktemp)" || return 1
  cat > "$tmp"
  _proxy_root install -m 0644 "$tmp" "$file"
  rm -f "$tmp"
}

_proxy_lc() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]'
}

_proxy_load_conf() {
  [ -f "$_PROXY_CONF" ] || return 1
  # shellcheck disable=SC1090
  . "$_PROXY_CONF"

  PROXY_DEFAULT="$(_proxy_lc "${PROXY_DEFAULT:-mobaxterm}")"
  : "${PROXY_MOBAXTERM:=127.0.0.1:7890}"
  : "${PROXY_MIHOMO:=127.0.0.1:50000}"
  : "${PROXY_NO_PROXY:=localhost,127.0.0.1,::1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,10.8.0.0/24,192.168.50.0/24,.local}"
  : "${DOCKER_PROXY_ENABLED:=true}"
  : "${BT_RESTART_ON_CHANGE:=true}"
}

_proxy_provider_addr_by_name() {
  case "$(_proxy_lc "$1")" in
    mobaxterm|moba|7890) printf '%s' "$PROXY_MOBAXTERM" ;;
    mihomo|vps|50000) printf '%s' "$PROXY_MIHOMO" ;;
    *) return 1 ;;
  esac
}

_proxy_provider_addr() {
  _proxy_provider_addr_by_name "$PROXY_DEFAULT"
}

_proxy_provider_label() {
  case "$PROXY_DEFAULT" in
    mobaxterm) printf 'MobaXterm' ;;
    mihomo) printf 'VPS mihomo' ;;
    *) printf '%s' "$PROXY_DEFAULT" ;;
  esac
}

_proxy_http_url() {
  printf 'http://%s' "$(_proxy_provider_addr)"
}

_proxy_socks_url() {
  printf 'socks5h://%s' "$(_proxy_provider_addr)"
}

_proxy_port_open() {
  local addr="$1" host port
  host="${addr%:*}"
  port="${addr##*:}"
  timeout 1 bash -c "</dev/tcp/${host}/${port}" >/dev/null 2>&1
}

_proxy_export_env() {
  local http="$1" socks="$2" no_proxy="$3"

  export http_proxy="$http"
  export https_proxy="$http"
  export HTTP_PROXY="$http"
  export HTTPS_PROXY="$http"
  export all_proxy="$socks"
  export ALL_PROXY="$socks"
  export no_proxy="$no_proxy"
  export NO_PROXY="$no_proxy"
}

_proxy_unset_env() {
  unset http_proxy https_proxy ftp_proxy all_proxy no_proxy
  unset HTTP_PROXY HTTPS_PROXY FTP_PROXY ALL_PROXY NO_PROXY
}

_proxy_set_shell_profile() {
  local http="$1" socks="$2" no_proxy="$3"

  cat <<ENV | _proxy_write_root_file "$_PROXY_ENV"
# Generated by proxy-tools. Do not edit manually.
export http_proxy="$http"
export https_proxy="$http"
export HTTP_PROXY="$http"
export HTTPS_PROXY="$http"
export all_proxy="$socks"
export ALL_PROXY="$socks"
export no_proxy="$no_proxy"
export NO_PROXY="$no_proxy"
ENV
}

_proxy_unset_shell_profile() {
  _proxy_root rm -f "$_PROXY_ENV"
}

_proxy_set_apt() {
  local http="$1"
  cat <<APT | _proxy_write_root_file "$_APT_CONF"
Acquire::http::Proxy "$http";
Acquire::https::Proxy "$http";
APT
}

_proxy_unset_apt() {
  _proxy_root rm -f "$_APT_CONF"
}

_proxy_set_git() {
  local http="$1"
  if command -v git >/dev/null 2>&1; then
    git config --global http.proxy "$http"
    git config --global https.proxy "$http"
  fi
}

_proxy_unset_git() {
  if command -v git >/dev/null 2>&1; then
    git config --global --unset-all http.proxy 2>/dev/null || true
    git config --global --unset-all https.proxy 2>/dev/null || true
  fi
}

_proxy_set_wget() {
  local http="$1"
  local tmp
  tmp="$(mktemp)" || return 1

  if [ -f "$_WGET_CONF" ]; then
    awk '
      /^# BEGIN proxy-tools$/ {skip=1; next}
      /^# END proxy-tools$/ {skip=0; next}
      skip != 1 {print}
    ' "$_WGET_CONF" > "$tmp"
  else
    : > "$tmp"
  fi

  cat >> "$tmp" <<WGET
# BEGIN proxy-tools
use_proxy = on
http_proxy = $http
https_proxy = $http
ftp_proxy = $http
# END proxy-tools
WGET

  _proxy_root install -m 0644 "$tmp" "$_WGET_CONF"
  rm -f "$tmp"
}

_proxy_unset_wget() {
  [ -f "$_WGET_CONF" ] || return 0

  local tmp
  tmp="$(mktemp)" || return 1

  awk '
    /^# BEGIN proxy-tools$/ {skip=1; next}
    /^# END proxy-tools$/ {skip=0; next}
    skip != 1 {print}
  ' "$_WGET_CONF" > "$tmp"

  _proxy_root install -m 0644 "$tmp" "$_WGET_CONF"
  rm -f "$tmp"
}

_proxy_set_docker() {
  local http="$1" no_proxy="$2"
  _proxy_root mkdir -p "$_DOCKER_CONF_DIR"

  cat <<DOCKER | _proxy_write_root_file "$_DOCKER_CONF"
[Service]
Environment="HTTP_PROXY=$http" "HTTPS_PROXY=$http" "NO_PROXY=$no_proxy"
DOCKER

  _proxy_root systemctl daemon-reload 2>/dev/null || true
}

_proxy_unset_docker() {
  _proxy_root rm -f "$_DOCKER_CONF"
  _proxy_root systemctl daemon-reload 2>/dev/null || true
}

_proxy_docker_on() {
  _proxy_load_conf
  _proxy_set_docker "$(_proxy_http_url)" "$PROXY_NO_PROXY"
  echo "Docker 代理配置已写入。需要重启 Docker 后才会生效。"
}

_proxy_docker_off() {
  _proxy_unset_docker
  echo "Docker 代理配置已删除。需要重启 Docker 后才会彻底生效。"
}

_proxy_docker_restart() {
  if command -v systemctl >/dev/null 2>&1 && systemctl list-unit-files 2>/dev/null | grep -q '^docker\.service'; then
    _proxy_root systemctl restart docker
    echo "Docker 已重启。"
  else
    echo "未发现 docker.service，已跳过。"
  fi
}

_proxy_restart_bt() {
  if command -v bt >/dev/null 2>&1; then
    _proxy_root bt restart
  elif [ -x /etc/init.d/bt ]; then
    _proxy_root /etc/init.d/bt restart
  elif command -v systemctl >/dev/null 2>&1 && systemctl list-unit-files 2>/dev/null | grep -q '^bt\.service'; then
    _proxy_root systemctl restart bt
  else
    echo "未找到宝塔 BT 重启命令，已跳过。"
  fi
}

_proxy_shell_value() {
  printf '%s' "${http_proxy:-${HTTP_PROXY:-}}"
}

_proxy_profile_value() {
  [ -f "$_PROXY_ENV" ] || return 0
  awk -F'"' '/export http_proxy=/{print $2; exit}' "$_PROXY_ENV" 2>/dev/null
}

_proxy_apt_value() {
  [ -f "$_APT_CONF" ] || return 0
  awk -F'"' '/Acquire::http::Proxy/{print $2; exit}' "$_APT_CONF" 2>/dev/null
}

_proxy_git_value() {
  command -v git >/dev/null 2>&1 || return 0
  git config --global --get http.proxy 2>/dev/null || true
}

_proxy_wget_value() {
  [ -f "$_WGET_CONF" ] || return 0
  awk -F= '/^[[:space:]]*http_proxy[[:space:]]*=/{v=$2; gsub(/^[ \t]+|[ \t]+$/, "", v); print v; exit}' "$_WGET_CONF" 2>/dev/null
}

_proxy_docker_config_value() {
  [ -f "$_DOCKER_CONF" ] || return 0
  grep -o 'HTTP_PROXY=[^" ]*' "$_DOCKER_CONF" 2>/dev/null | head -n1 | cut -d= -f2-
}

_proxy_docker_runtime_value() {
  command -v systemctl >/dev/null 2>&1 || return 0
  systemctl show -p Environment --value docker 2>/dev/null | tr ' ' '\n' | awk -F= '$1=="HTTP_PROXY"{print $2; exit}'
}

_proxy_bt_value() {
  local pids pid val
  pids="$(pgrep -f '/www/server/panel|BT-Panel|Bt-Panel|BTPanel' 2>/dev/null || true)"

  for pid in $pids; do
    [ -r "/proc/$pid/environ" ] || continue
    val="$(tr '\0' '\n' < "/proc/$pid/environ" 2>/dev/null | awk -F= '/^(http_proxy|HTTP_PROXY)=/{print $2; exit}')"
    if [ -n "$val" ]; then
      printf '%s' "$val"
      return 0
    fi
  done

  return 0
}

_proxy_label_value() {
  local value="$1" current="$2"

  if [ -z "$value" ]; then
    printf '关闭'
  elif [ "$value" = "$current" ]; then
    printf '开启（当前源）'
  else
    printf '开启（其他源：%s）' "$value"
  fi
}

_proxy_summary_state() {
  local current="$1" shell_v="$2" profile_v="$3" apt_v="$4" git_v="$5" wget_v="$6"
  local total=5 on=0 same=0

  for v in "$shell_v" "$profile_v" "$apt_v" "$git_v" "$wget_v"; do
    if [ -n "$v" ]; then
      on=$((on + 1))
      [ "$v" = "$current" ] && same=$((same + 1))
    fi
  done

  if [ "$on" -eq 0 ]; then
    printf '未开启'
  elif [ "$same" -eq "$total" ]; then
    printf '已开启'
  else
    printf '部分开启 / 源不一致'
  fi
}

_proxy_on() {
  _proxy_load_conf

  local http socks no_proxy
  http="$(_proxy_http_url)"
  socks="$(_proxy_socks_url)"
  no_proxy="$PROXY_NO_PROXY"

  _proxy_export_env "$http" "$socks" "$no_proxy"
  _proxy_set_shell_profile "$http" "$socks" "$no_proxy"
  _proxy_set_apt "$http"
  _proxy_set_git "$http"
  _proxy_set_wget "$http"

  if [ "$DOCKER_PROXY_ENABLED" = "true" ]; then
    _proxy_set_docker "$http" "$no_proxy"
  fi

  echo "普通代理已开启：$http"

  if [ "$BT_RESTART_ON_CHANGE" = "true" ]; then
    echo "正在重启 BT，让宝塔继承当前代理环境..."
    _proxy_restart_bt || true
  fi

  echo "提示：Docker 配置已写入，但 Docker daemon 需要单独重启才会生效。"
}

_proxy_off() {
  _proxy_load_conf

  _proxy_unset_env
  _proxy_unset_shell_profile
  _proxy_unset_apt
  _proxy_unset_git
  _proxy_unset_wget

  if [ "$DOCKER_PROXY_ENABLED" = "true" ]; then
    _proxy_unset_docker
  fi

  echo "普通代理已关闭。"

  if [ "$BT_RESTART_ON_CHANGE" = "true" ]; then
    echo "正在重启 BT，让宝塔清掉代理环境..."
    _proxy_restart_bt || true
  fi

  echo "提示：Docker 代理配置已删除，但 Docker daemon 需要单独重启才会彻底生效。"
}

_proxy_use() {
  _proxy_load_conf

  local raw="${1:-}" provider tmp

  case "$(_proxy_lc "$raw")" in
    1|m|moba|mobaxterm|7890) provider="mobaxterm" ;;
    2|h|mi|mihomo|vps|50000) provider="mihomo" ;;
    "")
      echo "用法：proxy-use mobaxterm | mihomo"
      return 1
      ;;
    *)
      echo "未知代理源：$raw"
      echo "可用：mobaxterm / mihomo"
      return 1
      ;;
  esac

  tmp="$(mktemp)" || return 1

  awk -v p="$provider" '
    BEGIN {done=0}
    /^PROXY_DEFAULT=/ {print "PROXY_DEFAULT=\"" p "\""; done=1; next}
    {print}
    END {if (done==0) print "PROXY_DEFAULT=\"" p "\""}
  ' "$_PROXY_CONF" > "$tmp"

  _proxy_root install -m 0644 "$tmp" "$_PROXY_CONF"
  rm -f "$tmp"

  echo "默认代理源已切换为：$provider"
}

# BEGIN proxy-tools-v25-cn-ui
_ui_color_init() {
  if [ -t 1 ] && [ -z "${NO_COLOR:-}" ] && command -v tput >/dev/null 2>&1 && [ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]; then
    C_RESET="$(tput sgr0)"
    C_BOLD="$(tput bold)"
    C_DIM="$(tput dim 2>/dev/null || true)"
    C_RED="$(tput setaf 1)"
    C_GREEN="$(tput setaf 2)"
    C_YELLOW="$(tput setaf 3)"
    C_BLUE="$(tput setaf 4)"
    C_MAGENTA="$(tput setaf 5)"
    C_CYAN="$(tput setaf 6)"
    C_WHITE="$(tput setaf 7)"
  else
    C_RESET=""
    C_BOLD=""
    C_DIM=""
    C_RED=""
    C_GREEN=""
    C_YELLOW=""
    C_BLUE=""
    C_MAGENTA=""
    C_CYAN=""
    C_WHITE=""
  fi
}

_ui_color_init

_ui_rule() {
  printf '%b\n' "${C_DIM}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${C_RESET}"
}

_ui_title() {
  printf '\n%b\n' "${C_CYAN}${C_BOLD}◆ $1${C_RESET}"
  _ui_rule
}

_ui_header() {
  printf '%b\n' "${C_CYAN}${C_BOLD}"
  printf '   _____ _____   ____                      _____           _            \n'
  printf '  / ____/ ____| |  _ \\                    / ____|         | |           \n'
  printf ' | (___| |  __  | |_) | __ ___  ___   _  | |     ___ _ __ | |_ ___ _ __ \n'
  printf '  \\___ \\ | |_ | |  __/ "__/ _ \\/ __| | | | |    / _ \\ "_ \\| __/ _ \\ "__|\n'
  printf '  ____) |__| |  | |  | | | (_) \\__ \\ |_| | |___|  __/ | | | ||  __/ |   \n'
  printf ' |_____/_____|  |_|  |_|  \\___/|___/\\__, |\\_____\\___|_| |_|\\__\\___|_|   \n'
  printf '                                      __/ |                              \n'
  printf '                                     |___/                               \n'
  printf '%b' "${C_RESET}"
  printf '%b\n' "${C_DIM}                  统一代理控制台 · proxy-on / proxy-off / proxy-use / proxy-status${C_RESET}"
}

_ui_state_text() {
  case "$1" in
    "已开启")
      printf '%b' "${C_GREEN}${C_BOLD}● 已开启${C_RESET}  ${C_GREEN}当前代理已完整启用${C_RESET}"
      ;;
    "未开启")
      printf '%b' "${C_RED}${C_BOLD}● 未开启${C_RESET} ${C_DIM}当前代理未启用${C_RESET}"
      ;;
    *)
      printf '%b' "${C_YELLOW}${C_BOLD}● 部分开启${C_RESET} ${C_YELLOW}有模块开启，或代理源不一致${C_RESET}"
      ;;
  esac
}

_ui_port_text() {
  local addr="$1"
  if _proxy_port_open "$addr"; then
    printf '%b' "${C_GREEN}● 可连接${C_RESET}"
  else
    printf '%b' "${C_RED}● 不可连接${C_RESET}"
  fi
}

_ui_module_text() {
  local value="$1"
  local current="$2"

  if [ -z "$value" ]; then
    printf '%b' "${C_RED}● 关闭${C_RESET}"
  elif [ "$value" = "$current" ]; then
    printf '%b' "${C_GREEN}● 开启${C_RESET} ${C_DIM}${value}${C_RESET}"
  else
    printf '%b' "${C_YELLOW}● 其他源${C_RESET} ${C_DIM}${value}${C_RESET}"
  fi
}

_ui_kv() {
  local key="$1"
  local value="$2"
  printf '  %b%-16s%b %b\n' "${C_DIM}" "$key" "${C_RESET}" "$value"
}

_ui_source_row() {
  local index="$1" key="$2" name="$3" addr="$4" role
  if [ "$PROXY_DEFAULT" = "$key" ]; then
    role="${C_GREEN}${C_BOLD}当前使用${C_RESET}"
  else
    role="${C_DIM}备用${C_RESET}"
  fi
  printf '  %b[%s]%b %-14s %b%-22s%b %-14b %b\n' \
    "${C_CYAN}" "$index" "${C_RESET}" \
    "$name" \
    "${C_MAGENTA}" "$addr" "${C_RESET}" \
    "$(_ui_port_text "$addr")" \
    "$role"
}

_ui_module_row() {
  local name="$1" value="$2" current="$3"
  printf '  %-18s %b\n' "$name" "$(_ui_module_text "$value" "$current")"
}

_proxy_status() {
  _proxy_load_conf

  local provider addr http socks
  local shell_v profile_v apt_v git_v wget_v docker_conf_v docker_run_v bt_v
  local summary

  provider="$(_proxy_provider_label)"
  addr="$(_proxy_provider_addr)"
  http="$(_proxy_http_url)"
  socks="$(_proxy_socks_url)"

  shell_v="$(_proxy_shell_value)"
  profile_v="$(_proxy_profile_value)"
  apt_v="$(_proxy_apt_value)"
  git_v="$(_proxy_git_value)"
  wget_v="$(_proxy_wget_value)"
  docker_conf_v="$(_proxy_docker_config_value)"
  docker_run_v="$(_proxy_docker_runtime_value)"
  bt_v="$(_proxy_bt_value)"

  summary="$(_proxy_summary_state "$http" "$shell_v" "$profile_v" "$apt_v" "$git_v" "$wget_v")"

  _ui_header
  _ui_title "当前状态"
  _ui_kv "总体状态" "$(_ui_state_text "$summary")"
  _ui_kv "默认代理源" "${C_MAGENTA}${C_BOLD}${provider}${C_RESET}"
  _ui_kv "HTTP 代理" "${C_GREEN}${http}${C_RESET}"
  _ui_kv "SOCKS 代理" "${C_GREEN}${socks}${C_RESET}"
  _ui_kv "当前端口" "${C_MAGENTA}${addr}${C_RESET}  $(_ui_port_text "$addr")"
  _ui_kv "直连规则" "${C_DIM}局域网 / Docker / WireGuard / EasyTier / 本地域名 / 自定义域名${C_RESET}"

  _ui_title "代理源"
  _ui_source_row "1" "mobaxterm" "MobaXterm" "$PROXY_MOBAXTERM"
  _ui_source_row "2" "mihomo" "VPS mihomo" "$PROXY_MIHOMO"

  _ui_title "模块状态"
  _ui_module_row "当前终端" "$shell_v" "$http"
  _ui_module_row "持久终端" "$profile_v" "$http"
  _ui_module_row "APT" "$apt_v" "$http"
  _ui_module_row "Git" "$git_v" "$http"
  _ui_module_row "Wget" "$wget_v" "$http"
  _ui_module_row "Docker 配置" "$docker_conf_v" "$http"
  _ui_module_row "Docker 运行时" "$docker_run_v" "$http"
  _ui_module_row "BT 面板进程" "$bt_v" "$http"

  _ui_title "快捷命令"
  printf '  %bproxy-on%b      %bproxy-off%b      %bproxy-status%b\n' \
    "${C_GREEN}" "${C_RESET}" \
    "${C_RED}" "${C_RESET}" \
    "${C_BLUE}" "${C_RESET}"
  printf '  %bproxy-use mobaxterm%b      %bproxy-use mihomo%b      %bdocker-proxy-restart%b\n' \
    "${C_MAGENTA}" "${C_RESET}" \
    "${C_MAGENTA}" "${C_RESET}" \
    "${C_YELLOW}" "${C_RESET}"
  printf '  %bNO_COLOR=1 proxy%b\n' "${C_DIM}" "${C_RESET}"
}

_proxy_menu_panel() {
  _ui_title "控制面板"
  printf '  %b1%b  %-16s %b%s%b\n' "${C_GREEN}${C_BOLD}" "${C_RESET}" "开启代理" "${C_DIM}" "当前终端 + APT + Git + Wget + Docker 配置 + 重启 BT" "${C_RESET}"
  printf '  %b2%b  %-16s %b%s%b\n' "${C_RED}${C_BOLD}" "${C_RESET}" "关闭代理" "${C_DIM}" "清理终端 / APT / Git / Wget / Docker 配置 / 重启 BT" "${C_RESET}"
  printf '  %b3%b  %-16s %b%s%b\n' "${C_MAGENTA}${C_BOLD}" "${C_RESET}" "切换代理源" "${C_DIM}" "MobaXterm / VPS mihomo" "${C_RESET}"
  printf '\n'
  printf '  %b4%b  %-16s %b%s%b\n' "${C_YELLOW}${C_BOLD}" "${C_RESET}" "重启 Docker" "${C_DIM}" "让 Docker 代理配置立即生效" "${C_RESET}"
  printf '  %b5%b  %-16s %b%s%b\n' "${C_YELLOW}${C_BOLD}" "${C_RESET}" "重启 BT 面板" "${C_DIM}" "让宝塔重新继承当前环境变量" "${C_RESET}"
  printf '\n'
  printf '  %b6%b  %-16s\n' "${C_BLUE}${C_BOLD}" "${C_RESET}" "刷新状态"
  printf '  %b0%b  %-16s\n' "${C_DIM}" "${C_RESET}" "退出"
}

_proxy_switch_menu() {
  _proxy_load_conf
  _ui_header
  _ui_title "切换代理源"
  _ui_kv "当前默认源" "${C_MAGENTA}${C_BOLD}${PROXY_DEFAULT}${C_RESET}"
  echo
  _ui_source_row "1" "mobaxterm" "MobaXterm" "$PROXY_MOBAXTERM"
  _ui_source_row "2" "mihomo" "VPS mihomo" "$PROXY_MIHOMO"
  echo

  local c
  read -r -p "请选择默认代理源 > " c

  case "$c" in
    1) _proxy_use mobaxterm ;;
    2) _proxy_use mihomo ;;
    *) echo "已取消。"; return 0 ;;
  esac

  echo
  read -r -p "是否立刻按新源重新开启代理？[y/N] " c
  case "$(_proxy_lc "$c")" in
    y|yes) _proxy_on ;;
  esac
}

_proxy_pause() {
  [ -t 0 ] || return 0
  echo
  read -r -p "按回车返回控制台..." _
}

_proxy_menu() {
  while true; do
    if [ -t 1 ] && command -v clear >/dev/null 2>&1; then
      clear
    fi

    _proxy_status
    _proxy_menu_panel
    echo

    local choice
    read -r -p "请选择 > " choice

    case "$choice" in
      1) _proxy_on; _proxy_pause ;;
      2) _proxy_off; _proxy_pause ;;
      3) _proxy_switch_menu; _proxy_pause ;;
      4) _proxy_docker_restart; _proxy_pause ;;
      5) _proxy_restart_bt; _proxy_pause ;;
      6) continue ;;
      0|q|Q) return 0 ;;
      *) echo "无效选择。"; _proxy_pause ;;
    esac
  done
}
# END proxy-tools-v25-cn-ui
